---
  - name: Include OS family specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_os_family }}.yml"

  - import_tasks: metricbeat_pre.yml
  - import_tasks: metricbeat_install.yml

  - block:
    - import_tasks: metricbeat_search_config.yml
    - import_tasks: metricbeat_post.yml
    tags: metricbeat-config
